DEFAULT_DECISION_ORDER = [
    "deny",
    "manual_review",
    "condition_allow",
    "allow",
]

SUPPORTED_DECISIONS = set(DEFAULT_DECISION_ORDER)

EU_EEA_COUNTRIES = {
    "AT",
    "BE",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "DE",
    "GR",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LI",
    "LT",
    "LU",
    "MT",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "SE",
}

AWS_REGION_TO_COUNTRY = {
    "af-south-1": "ZA",
    "ap-east-1": "HK",
    "ap-northeast-1": "JP",
    "ap-northeast-2": "KR",
    "ap-northeast-3": "JP",
    "ap-south-1": "IN",
    "ap-south-2": "IN",
    "ap-southeast-1": "SG",
    "ap-southeast-2": "AU",
    "ap-southeast-3": "ID",
    "ap-southeast-4": "AU",
    "ca-central-1": "CA",
    "ca-west-1": "CA",
    "eu-central-1": "DE",
    "eu-central-2": "CH",
    "eu-north-1": "SE",
    "eu-south-1": "IT",
    "eu-south-2": "ES",
    "eu-west-1": "IE",
    "eu-west-2": "UK",
    "eu-west-3": "FR",
    "il-central-1": "IL",
    "me-central-1": "AE",
    "me-south-1": "BH",
    "br-sao-paulo-dc": "BR",
    "sa-east-1": "BR",
    "sa-riyadh-dc": "SA",
    "sa-jeddah-dc": "SA",
    "sa-dammam-dc": "SA",
    "tw-taipei-dc": "TW",
    "us-east-1": "US",
    "us-east-2": "US",
    "us-west-1": "US",
    "us-west-2": "US",
}

EU_ADEQUACY_COUNTRIES = {
    "AD",
    "AR",
    "BR",
    "CA",
    "FO",
    "GG",
    "IL",
    "IM",
    "JP",
    "JE",
    "KR",
    "NZ",
    "CH",
    "UK",
    "UY",
}

FIELD_LABELS_KO = {
    "access_control_in_place": "접근통제",
    "adequacy_decision_exists": "적정성 결정 여부",
    "adequacy_decision_country_only": "국가 단위 적정성 결정 여부",
    "adequacy_scope_confirmed": "적정성 적용 범위 확인 여부",
    "adequate_protection_confirmed": "적정 보호 수준 확인",
    "anpd_scc_migration_completed": "ANPD SCC 전환 완료",
    "appropriate_safeguards_available": "적절한 보호조치 확보 여부",
    "appropriate_transfer_mechanism_available": "국제이전 보호 메커니즘 확보",
    "article8_notice_provided": "대만 제8조 고지 제공",
    "article9_source_notice_provided": "대만 제9조 출처 고지 제공",
    "baseline_security_controls_ready": "기본 보안 통제 충족 여부",
    "bcr_in_place": "BCR 체결 여부",
    "breach_notification_ready_72h": "72시간 내 침해 신고 준비",
    "breach_notification_process_ready": "침해 통지 절차",
    "binding_common_rules_approved": "승인된 공통구속규칙",
    "binding_corporate_rules_anpd_approved": "ANPD 승인 BCR",
    "binding_corporate_rules_used": "BCR 사용 여부",
    "breach_response_72h_ready": "72시간 내 침해 대응 준비",
    "certification_or_code_in_place": "인증 또는 행동강령 보호조치",
    "certification_or_code_approved": "ANPD 인정 인증·행동강령",
    "collection_processing_basis": "수집·처리 법적 근거",
    "commissioned_processor_terms_in_place": "위탁 처리 조건 문서화",
    "contains_sensitive_data": "민감정보 포함 여부",
    "contains_article6_sensitive_data": "대만 제6조 민감정보 포함 여부",
    "consent_withdrawal_process_ready": "동의 철회 대응 절차",
    "contract_necessity_disclosed_or_notified": "계약상 위탁·보관 공개 또는 통지",
    "controller_processor_roles_defined": "컨트롤러·프로세서 역할 정의",
    "cross_border_notice_provided": "국외이전 고지 제공",
    "cross_border_transfer": "대만 국외전송 여부",
    "current_region": "현재 처리 리전",
    "data_accuracy_review_completed": "개인정보 정확성 점검",
    "data_minimized": "데이터 최소화",
    "data_subject_connection": "정보주체 연결성",
    "data_subject_region": "정보주체 지역",
    "data_subject_rights_process_ready": "정보주체 권리 대응 절차",
    "data_subject_rights_request_ready": "정보주체 권리 요청 대응",
    "dataset_name": "데이터셋 이름",
    "derogation_type": "예외 이전 유형",
    "derogation_used": "제49조 예외 이전 사용 여부",
    "dpa_in_place": "DPA 체결 여부",
    "dpo_or_encarregado_assigned": "LGPD encarregado 지정",
    "dpo_assigned": "개인정보 보호 책임자 지정",
    "dpo_required": "개인정보 보호 책임자 필요 여부",
    "dpia_completed": "DPIA 완료",
    "dpia_required": "DPIA 필요 여부",
    "encryption_at_rest": "저장 시 암호화",
    "encryption_in_transit": "전송 시 암호화",
    "eu_adequacy_decision_exists": "EU GDPR 적정성 결정 여부",
    "gdpr_eu_data_subjects_included": "GDPR EU/EEA 정보주체 포함",
    "gdpr_eu_establishment_involved": "GDPR EU/EEA 사업장 관여",
    "gdpr_monitors_eu_behavior": "GDPR EU/EEA 행동 모니터링",
    "gdpr_offers_goods_or_services_to_eu": "GDPR EU/EEA 상품·서비스 제공",
    "gdpr_onward_transfer_safeguard_ready": "GDPR 후속 이전 보호조치",
    "gdpr_processor_contract_ready": "GDPR processor 계약 준비",
    "incident_response_in_place": "침해 대응 절차",
    "is_third_country_transfer": "제3국 이전 여부",
    "is_automated_decision_only": "완전 자동화 결정 여부",
    "lawful_basis": "적법 근거",
    "lgpd_scope_applies": "LGPD 적용 범위 해당 여부",
    "lgpd_brazil_data_subjects_included": "LGPD 브라질 정보주체 포함",
    "lgpd_data_collected_in_brazil": "LGPD 브라질 내 수집",
    "lgpd_data_subject_rights_process_ready": "LGPD 정보주체 권리 절차",
    "lgpd_international_transfer_mechanism_ready": "LGPD 국제이전 메커니즘",
    "lgpd_services_to_brazil_residents": "LGPD 브라질 대상 서비스",
    "explicit_consent_for_sensitive_data": "민감정보 명시적 동의",
    "full_transfer_clauses_request_ready": "전체 이전 조항 제공 요청 대응",
    "has_unique_identifier": "고유식별정보 포함 여부",
    "human_review_available": "인적 개입 가능 여부",
    "international_transfer_transparency_document_available": "국제이전 투명성 문서",
    "large_scale_or_high_risk_processing": "대규모 또는 고위험 처리",
    "legacy_contractual_clauses_used": "기존 계약조항 사용",
    "major_national_interest_involved": "중대 국가이익 관련성",
    "marketing_optout_mechanism_ready": "마케팅 수신거부 준비",
    "onward_transfer_controls": "재이전 통제",
    "other_safeguards_in_place": "기타 제46조 보호조치",
    "pdpl_onward_transfer_planned": "Saudi PDPL 후속 이전 예정",
    "pdpl_saudi_controller_or_processor_involved": "Saudi PDPL 사우디 controller/processor 관여",
    "pdpl_saudi_data_subjects_included": "Saudi PDPL 사우디 정보주체 포함",
    "pdpl_scc_or_adequacy_ready": "Saudi PDPL SCC 또는 적정성 경로",
    "pdpl_sensitive_or_special_data": "Saudi PDPL 민감정보 포함",
    "pdpl_transfer_regulation_safeguards_ready": "Saudi PDPL 이전 보호조치",
    "pipa_certified_recipient": "PIPA 인증 수령자",
    "pipa_cross_border_notice_items_ready": "PIPA 국외이전 고지 항목 준비",
    "pipa_domestic_agent_or_establishment": "PIPA 국내대리인·사업장 관련성",
    "pipa_equivalence_recognition_exists": "PIPA 동등 보호수준 인정 여부",
    "pipa_effect_on_korean_data_subjects": "PIPA 한국 정보주체 영향",
    "pipa_korean_data_subjects_included": "PIPA 한국 정보주체 포함",
    "pipa_privacy_policy_disclosure_ready": "PIPA 처리방침 공개 준비",
    "pipa_services_to_korean_users": "PIPA 한국 이용자 대상 서비스",
    "pipa_transfer_basis_available": "PIPA 국외이전 허용 경로",
    "privacy_notice_updated": "개인정보 처리방침 최신화",
    "privacy_notice_available": "개인정보 고지 제공",
    "privacy_officer_assigned": "개인정보 보호책임자 지정",
    "processing_impact_assessment_completed": "처리 영향평가 완료",
    "processing_legal_basis": "처리 적법 근거",
    "processing_purpose_defined": "처리 목적 정의",
    "privacy_by_design_review_completed": "프라이버시 설계 검토 완료",
    "public_source_objection_handled": "공개출처 이의 처리",
    "processor_sufficient_guarantees": "수탁자 충분한 보증",
    "processor_agreement_in_place": "프로세서 계약 체결",
    "processor_compliance_verified": "프로세서 준수 검증",
    "recipient_country_protection_adequate": "수령국 보호수준 충분성",
    "recipient_us_dpf_certified": "미국 수령자 DPF 인증 여부",
    "records_of_processing_exists": "처리 활동 기록부",
    "retention_period_defined": "보관기간 정의",
    "scc_in_place": "SCC 체결 여부",
    "security_incident_response_ready": "보안사고 대응 준비",
    "security_maintenance_measures_ready": "보안 유지 조치 준비",
    "sensitive_data_basis": "민감정보 처리 근거",
    "sensitive_data_exception_basis": "대만 민감정보 예외 근거",
    "sensitive_data_legal_basis": "LGPD 민감정보 처리 근거",
    "separate_consent_for_transfer": "국외이전 별도 동의",
    "special_category_condition_met": "민감정보 예외 요건 충족",
    "standard_contractual_clauses_in_place": "표준계약조항 체결",
    "standard_contractual_clauses_full_unaltered": "SCC 전체·무변경 채택",
    "subsequent_transfer_controls_in_place": "후속 이전 통제",
    "subsequent_transfer_expected": "후속 이전 예상",
    "subprocessor_controls_in_place": "하위처리자 통제",
    "subprocessor_or_onward_transfer_controls": "하위처리자·재이전 통제",
    "supplemental_measures_documented": "보완조치 문서화",
    "target_country": "대상 국가",
    "target_country_known": "대상 국가 식별 여부",
    "target_residents_included": "목표지 정보주체 포함",
    "target_region": "대상 리전",
    "taiwan_circumvention_transfer_risk": "대만 PDPA 우회 이전 위험",
    "taiwan_data_subjects_included": "대만 정보주체 포함",
    "taiwan_recipient_country_protection_adequate": "대만 수신국 보호수준 충분성",
    "taiwan_recipient_processing_in_taiwan": "대만 내 수신자 처리",
    "taiwan_sector_restriction_possible": "대만 산업별 제한 가능성",
    "taiwan_security_maintenance_ready": "대만 보안 유지 조치",
    "third_country_circumvention_risk": "제3국 우회 위험",
    "third_party_provision_consent_or_basis": "제3자 제공 동의 또는 근거",
    "third_party_sharing": "제3자 제공 여부",
    "transfer_outside_brazil": "브라질 밖 이전 여부",
    "transfer_outside_korea": "한국 밖 이전 여부",
    "transfer_outside_taiwan": "대만 밖 이전 여부",
    "transfer_exception_type": "사우디 국외이전 예외 유형",
    "transfer_exception_used": "사우디 국외이전 예외 사용 여부",
    "transfer_disclosed_to_subject": "국외 이전 고지",
    "transfer_documented_in_ropa": "이전 사항 ROPA 반영",
    "transfer_impact_assessment_completed": "이전 영향 평가 완료",
    "transfer_outside_kingdom": "사우디 기준 국외 이전 여부",
    "transfer_protection_measures_ready": "국외이전 보호조치 준비",
    "transfer_risk_assessment_completed": "국외이전 위험평가 완료",
    "transfer_risk_assessment_required": "국외이전 위험평가 필요 여부",
    "transfer_safeguards_available": "이전 보호조치 확보 여부",
    "treaty_or_agreement_restriction_known": "조약·협정 제한",
    "treaty_or_statutory_transfer_basis": "조약·법률상 이전 근거",
    "unique_identifier_basis": "고유식별정보 처리 근거",
    "uses_processor": "외부 처리자 사용 여부",
    "uses_commissioned_processor": "위탁 처리자 사용 여부",
    "uses_data_for_marketing": "마케팅 이용 여부",
    "uses_resident_registration_number": "주민등록번호 처리 여부",
    "written_consent_for_sensitive_data": "민감정보 서면 동의",
    "large_scale_or_continuous_transfer": "대규모 또는 지속적 이전",
}
